root: true
env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends: 
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
plugins:
  - 'scoutradioz-eslint'
  - '@typescript-eslint'
parser: '@typescript-eslint/parser'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  NotificationCard: writable
  Confirm: writable
  PasswordPrompt: writable
  FormSubmission: writable
  $: readonly
  luxon: readonly
  window: writable
parserOptions:
  ecmaVersion: 2018
ignorePatterns: 
  - bundle.d.ts
rules:
  indent:
    - error
    - tab
    - SwitchCase: 1
  # linebreak-style:
  #   - error
  #   - windows
  quotes:
    - error
    - single
  semi:
    - error
    - always
  global-require: error
  no-new-require: error
  no-mixed-requires: error
  no-prototype-builtins: 0
  brace-style:
    - error
    - stroustrup
    - allowSingleLine: true
  # guard-for-in: 
  #   - warn
  no-useless-escape: 0
  scoutradioz-eslint/res-render-require-title:
    - error
  prefer-const: off
  no-unused-vars: off # Must be turned off because typescript-eslint/no-unused-vars supecedes this
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-unused-vars': 
    - warn
    - args: none
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/no-namespace': off
  '@typescript-eslint/ban-ts-comment': warn
  '@typescript-eslint/consistent-type-imports': 
    - warn
    -
      prefer: 'type-imports'
      disallowTypeAnnotations: true
      fixStyle: 'separate-type-imports'
