env:
  browser: true
  es6: true
  node: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {
  linebreak-style: 0,
  no-tabs: 0,
  eqeqeq: 0,
  indent: 0,
  no-trailing-spaces: 0,
  radix: 0,
  prefer-destructuring: [error, {object: false}],
  brace-style: [warn, stroustrup],
  consistent-return: 0,
  padded-blocks: 0,
  no-plusplus: 0,
  max-len: [warn, 130],
  camelcase: warn,
  no-underscore-dangle: 0,
  no-var: 0,
  vars-on-top: 0,
  no-prototype-builtins: 0,
  no-restricted-syntax: 0, #
  guard-for-in: 0, #Take a look at this for our code rework
  no-restricted-globals: 0, 
  no-redeclare: 0, #
}