service: 'scoutradioz-voyager'

frameworkVersion: "3"

plugins:
  - '@silvermine/serverless-plugin-cloudfront-lambda-edge'
  - serverless-s3-deploy

provider:
  name: aws
  runtime: nodejs16.x
  # lambdaHashingVersion: 20201221 (not necessary b/c 20201221 is used by default)
  region: us-east-1 #Lambda@Edge must be deployed in us-east-1
  stage: ${opt:stage, 'test'} # test, qa, and prod
  stackName: ScoutradiozVoyagerStack
  # https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml#api-gateway-v2-http-api
  # apiName: ScoutradiozVoyagerApi
  # endpointType: REGIONAL
  
  httpApi:
    name: 'ScoutradiozVoyagerApi'
    cors: true
package:
  individually: true
  patterns:
    - '!./**'
    - build/server/**
    - build/edge/**

custom:
  assets:
    auto: true
    targets:
      - bucket: 
          Ref: StaticAssets
        files:
          - source: ./build/assets/
            globs: 
              - '**'
            empty: true
            headers:
              CacheControl: max-age=31104000
          - source: ./build/prerendered/
            globs: 
              - '**'
            empty: true
            headers:
              CacheControl: max-age=60

functions:
  #SSR Function
  svelte:
    name: ${self:provider.stackName}-SvelteFunction
    reservedConcurrency: 5
    handler: build/server/serverless.handler
    memorySize: 256
    timeout: 15
    url: true
    events:
    # https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml#api-gateway-v2-http-api-1
    #   # HTTP API endpoint (API Gateway v1)
    #   - http:
    #     path: /
    #     method: get
    #     request:
    #       uri: http://voyager.scoutradioz.com/
    #       # Custom request mapping templates that overwrite default templates
    #       template:
    #         application/json: '{ "httpMethod" : "$context.httpMethod" }'
    #       # Optional define pass through behavior when content-type does not match any of the specified mapping templates
    #       passThrough: NEVER
      # HTTP API endpoint (API Gateway v2)
      - httpApi:
          method: GET
          path: /{param}
      - httpApi:
          method: POST
          path: /{param}
    environment: &lambdaEnvVariables
      TIER: test # should be updated somewhere else in code somehow later 
      UTILITIES_DEBUG: 'false'

  #Router Function
  edgeRouter:
    name: ${self:provider.stackName}-EdgeRouterFunction
    reservedConcurrency: 5
    handler: build/edge/router.handler
    memorySize: 128
    timeout: 1
    lambdaAtEdge:
      distribution: 'WebsiteDistribution'
      eventType: origin-request
    # environment: *lambdaEnvVariables # apparently not supported for lambda@edge

resources:
  Resources:
    StaticAssets:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:service}
        # cors:
        #   - AllowedHeaders: []
        #     AllowedMethods:
        #       - GET
        #     AllowedOrigins:
        #       - https://scoutradioz.com
        #       - https://www.scoutradioz.com
        #       - https://qa.scoutradioz.com
        #       - https://test.scoutradioz.com
        #       - https://voyager.scoutradioz.com
        #     ExposeHeaders":
        #       - x-amz-server-side-encryption
        #       - x-amz-request-id
        #       - x-amz-id-2
        #     MaxAgeSeconds: 86400
    StaticAssetsS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticAssets
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource:
                Fn::Join: ["", ["arn:aws:s3:::", { "Ref": "StaticAssets" }, "/*"]]

    WebsiteDistribution:
      Type: 'AWS::CloudFront::Distribution'
      Properties:
        DistributionConfig:
          Origins:
            -
              DomainName: !Select [2, !Split ["/", !GetAtt ["SvelteLambdaFunctionUrl", "FunctionUrl"]]]
              # DomainName: !GetAtt "HttpApi.ApiGatewayV2.DomainName"
              Id: default
              OriginCustomHeaders: 
                #Lambda@edge does not support ENV vars, so instead we have to pass in a customHeaders.
                -
                  HeaderName: 's3-host'
                  HeaderValue: '${self:service}.s3.amazonaws.com'
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: 'https-only'
          Enabled: true
          Comment: '${self:service} autogenerated with serverless'
          DefaultCacheBehavior:
            TargetOriginId: default
            Compress: true
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            CachedMethods:
              - GET
              - HEAD
              - OPTIONS
            ForwardedValues:
              Cookies:
                Forward: all
              QueryString: True
            ViewerProtocolPolicy: 'redirect-to-https'